USE DATABASE SHADOWTRACE_AI;
USE SCHEMA AML;

CREATE STAGE IF NOT EXISTS APP_STAGE DIRECTORY = (ENABLE = TRUE);
PUT file://app/streamlit_app.py @APP_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://environment.yml @APP_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;
PUT file://.streamlit/config.toml @APP_STAGE/.streamlit AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- Change COMPUTE_WH if your account uses another warehouse.
CREATE OR REPLACE STREAMLIT SHADOWTRACEAI_APP
  FROM @APP_STAGE
  MAIN_FILE = 'streamlit_app.py'
  QUERY_WAREHOUSE = COMPUTE_WH
  TITLE = 'ShadowTraceAI: AML Intelligence Copilot';
